### ISSUE TITLE
Basic Continuous Integration

### ISSUE THREAD

**Issue by Slyces** [CharlyCst/zephyr#16]
Run the test-suite on every `dev`/`master` PR

**Comment by CharlyCst** [comment]
I just saw the pipeline failure due to the fact that Wasmtime is missing from Github hosted runners, Node.js [is installed](https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md) though, a workaround would be to use it as runtime instead.
We may have to write some JS boilerplate but it is a good thing to test in multiple runtimes anyway.

**Comment by Slyces** [comment]
@CharlyCst I closed this issue for now as the basic behavior are functional, but we might discuss later improvements of this feature.
I'm creating a new epic (#25) to list the different challenges/features of a complere CI suite.
